---
- name: Create docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: ../docker-compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Start containers
  community.docker.docker_compose_v2:
    project_src: ../
    state: present
    recreate: always
    pull: missing