version: '3'

services:
  wordpress:
    image: wordpress:6.7.2-php8.2-apache
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_database
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - wordpress_database
    restart: always

  wordpress_database:
    image: mysql:9.2.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: